FinalProject/DemoApplication/Models/Employee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DemoApplication.Models
{
    public class Employee
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [MaxLength(100)]
        public string FirstName { get; set; }
        [MaxLength(100)]
        public string LastName { get; set; }
        [MaxLength(100)]
        public string City { get; set; }
        [MaxLength(10)]
        public string Zip { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

FinalProject/DemoApplication/Models/EmployeeSalary.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace DemoApplication.Models
{
    public class EmployeeSalary
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public DateTime SalaryDate { get; set; }
        public decimal Amount { get; set; }
        public DateTime CreatedDate { get; set; }
        public Employee Employee { get; set; }
    }
}

FinalProject/DemoApplication/Pages/Employee/Create.cshtml.cs
using DemoApplication.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoApplication.Pages.Employee
{
    public class CreateModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly ILogger<IndexModel> _logger;

        public CreateModel(IEmployeeRepository employeeRepository, ILogger<IndexModel> logger)
        {
            _employeeRepository = employeeRepository;
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Models.Employee Employee { get; set; } = default!;

        public IActionResult OnPost()
        {
            try
            {
                if (!ModelState.IsValid || _employeeRepository.GetEmployeeList() == null || Employee == null)
                {
                    return Page();
                }
                Employee.CreatedDate = DateTime.Now;
                _employeeRepository.Create(Employee);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
            }
            return RedirectToPage("./Index");
        }
    }
}

FinalProject/DemoApplication/Pages/Employee/Index.cshtml.cs
using AutoMapper;
using DemoApplication.DTOs;
using DemoApplication.Interfaces;
using DemoApplication.Repositories;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace DemoApplication.Pages.Employee
{
    public class IndexModel : PageModel
    {
        private readonly IEmployeeRepository _repository;
        private readonly IEmployeeSalaryRepository _repositorySalary;
        private readonly ILogger<IndexModel> _logger;
        private readonly IMapper _mapper;

        public IndexModel(IEmployeeRepository repository, ILogger<IndexModel> logger, IMapper mapper, IEmployeeSalaryRepository repositorySalary)
        {
            _repository = repository;
            _logger = logger;
            _mapper = mapper;
            _repositorySalary = repositorySalary;
        }

        public IList<Models.Employee> Employee { get; set; } = default!;

        public void OnGetAsync()
        {
            var employees = _repository.GetEmployeeList();
            if (employees != null)
            {
                Employee = employees;
            }
        }
        public IActionResult OnGetGetEditForm(int id)
        {
            var employee = _repository.GetEmployeeById(id);
            var employeeDTO = _mapper.Map<Models.Employee, EditEmployeeDTO>(employee);
            return Partial("_Edit", employeeDTO);
        }
        public IActionResult OnGetGetSalaries(int id)
        {
            var salaries = _repositorySalary.GetSalaryByEmployeeId(id);
            return Partial("_salaries", salaries);
        }
        public IActionResult OnPostEmpolyeeDetails(EditEmployeeDTO dto)
        {
            try
            {
                var employee = _mapper.Map<EditEmployeeDTO, Models.Employee>(dto);

                _repository.Edit(employee);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
            }
            return RedirectToAction("/Index");
        }
    }
}

FinalProject/DemoApplication/Pages/EmployeeSalary/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DemoApplication.Data;
using Microsoft.EntityFrameworkCore;
using DemoApplication.Interfaces;
using DemoApplication.DTOs;
using AutoMapper;

namespace DemoApplication.Pages.EmployeeSalary
{
    public class CreateModel : PageModel
    {
        private readonly IEmployeeSalaryRepository employeeSalaryRepository;
        private readonly IEmployeeRepository employeeRepository;
        private readonly IMapper _mapper;

        public CreateModel(IEmployeeSalaryRepository employeeSalaryRepository, IEmployeeRepository employeeRepository, IMapper mapper)
        {
            this.employeeSalaryRepository = employeeSalaryRepository;
            this.employeeRepository = employeeRepository;
            _mapper = mapper;
        }
        public List<SelectListItem> Items { get; set; }
        public async Task<IActionResult> OnGet()
        {
            var employees = employeeRepository.GetEmployeeList();
            Items = employees.Select(c => new SelectListItem() { Value = c.Id.ToString(), Text = c.FirstName + " " + c.LastName }).ToList();
            return Page();
        }

        [BindProperty]
        public EmployeeSalaryCreateDTO EmployeeSalary { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || employeeSalaryRepository.GetAll() == null || EmployeeSalary == null)
            {
                return Page();
            }
            var salary = _mapper.Map<EmployeeSalaryCreateDTO,Models.EmployeeSalary>(EmployeeSalary);
            salary.CreatedDate = DateTime.Now;
            await employeeSalaryRepository.CreateAsync(salary);

            return RedirectToPage("/Employee/Index");
        }
    }
}

FinalProject/DemoApplication/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace DemoApplication.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

FinalProject/DemoApplication/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoApplication.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

FinalProject/DemoApplication/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoApplication.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

FinalProject/DemoApplication/Pages/Employee/Create.cshtml
@page
@model DemoApplication.Pages.Employee.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Employee.FirstName" class="control-label"></label>
                <input asp-for="Employee.FirstName" class="form-control" />
                <span asp-validation-for="Employee.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee.LastName" class="control-label"></label>
                <input asp-for="Employee.LastName" class="form-control" />
                <span asp-validation-for="Employee.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee.City" class="control-label"></label>
                <input asp-for="Employee.City" class="form-control" />
                <span asp-validation-for="Employee.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee.Zip" class="control-label"></label>
                <input asp-for="Employee.Zip" class="form-control" />
                <span asp-validation-for="Employee.Zip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProject/DemoApplication/Pages/Employee/Index.cshtml
@page
@model DemoApplication.Pages.Employee.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h3 class="card-title">Employee List</h3>
<p>
    <a asp-page="Create">Create New</a>
</p>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    City
                </th>
                <th>
                    Zip
                </th>
                <th>
                    Created Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Employee)
            {
                <tr>
                    <td>
                        @item.FirstName
                    </td>
                    <td>
                        @item.LastName
                    </td>
                    <td>
                        @item.City
                    </td>
                    <td>
                        @item.Zip
                    </td>
                    <td>
                        @item.CreatedDate.ToString("MMM dd yyyy")
                    </td>
                    <td>
                        <a class="btn btn-info" href="#" onclick="editItem(@item.Id)">Edit</a>
                        <a class="btn btn-primary" href="#" onclick="viewSalary(@item.Id)">View Salary</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" id="EditModal" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-title">
        </div>
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit employee</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="EditModalContent">
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="\lib\jquery-validation\dist\jquery.validate.min.js"></script>
    <script>
        function editItem(itemId) {
            $.ajax({
                type: "GET",
                url: "?handler=GetEditForm&id=" + itemId, // Adjust the URL to match your route
                success: function (data) {
                    // Handle the response (e.g., show a modal with the edit form)
                    $("#EditModalContent").html(data);
                    $("#EditModal").modal("show");
                    $("#EditFormbtn").on("click", function () {
                        if (!$("#editForm").valid()) {
                            return false;
                        }
                        $("#editForm").submit();
                    })
                },
                error: function () {
                    // Handle errors
                    console.log("Error occurred while fetching edit form.");
                }
            });
        }
        function viewSalary(itemId) {
            $.ajax({
                type: "GET",
                url: "?handler=GetSalaries&id=" + itemId, // Adjust the URL to match your route
                success: function (data) {
                    // Handle the response (e.g., show a modal with the edit form)
                    $("#EditModalContent").html(data);
                    $("#EditModal").modal("show");
                },
                error: function () {
                    // Handle errors
                    console.log("Error occurred while fetching edit form.");
                }
            });
        }
    </script>
}

FinalProject/DemoApplication/Pages/Employee/_edit.cshtml
@using DemoApplication.DTOs;
@model EditEmployeeDTO
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<style>
    .error{
        color:red
    }
</style>
<div class="row">
    <div class="col-md-6">
        <form method="post" asp-page-handler="EmpolyeeDetails" id="editForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" required />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" required />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" required />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="Zip" class="control-label"></label>
                <input asp-for="Zip" class="form-control" required />
                <span asp-validation-for="Zip" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="button" id="EditFormbtn" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        
    </script>
}

FinalProject/DemoApplication/Pages/Employee/_salaries.cshtml
@model List<Models.EmployeeSalary>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    int srno = 1;
}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                Sr no
            </th>
            <th>
                Salary Date
            </th>
            <th>
                Amount
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@srno</td>
                <td>@item.SalaryDate</td>
                <td>@item.Amount</td>
            </tr>
            srno++;
        }
    </tbody>
</table>

FinalProject/DemoApplication/Pages/EmployeeSalary/Create.cshtml
@page
@model DemoApplication.Pages.EmployeeSalary.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>EmployeeSalary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                Employee
                <select asp-for="EmployeeSalary.EmployeeId" class="form-control" asp-items="Model.Items"></select>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeSalary.SalaryDate" class="control-label"></label>
                <input asp-for="EmployeeSalary.SalaryDate" class="form-control" />
                <span asp-validation-for="EmployeeSalary.SalaryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeSalary.Amount" class="control-label"></label>
                <input asp-for="EmployeeSalary.Amount" class="form-control" />
                <span asp-validation-for="EmployeeSalary.Amount" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="/Employee">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FinalProject/DemoApplication/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FinalProject/DemoApplication/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">DemoApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/EmployeeSalary/Create">Employee Salary</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DemoApplication - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>